<!doctype html>
<html lang="pt-br">
<head>
	<title>Positiv</title>
  <link rel="shortcut icon" href="<?php echo URL; ?>public/images/icons/favicon2.ico" />
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0"> 

	<script type="text/javascript" src="<?php echo URL; ?>public/js/jquery1-11.js"></script>
	<!-- <script type="text/javascript" src="<?php echo URL; ?>public/js/jquery-ui.min.js"></script> -->
	<script type="text/javascript" src="<?php echo URL; ?>public/js/default.js"></script>
	<script type="text/javascript" src="<?php echo URL; ?>public/js/igrejas.js"></script>

	<script type="text/javascript" src="<?php echo URL; ?>public/semantic.min.js"></script>
	<link rel="stylesheet" type="text/css" href="<?php echo URL; ?>public/semantic.min.css"/>

    <link rel="stylesheet" type="text/css" href="<?php echo URL; ?>public/css/default.css"/>
   <!-- <link rel="stylesheet" type="text/css" href="<?php echo URL; ?>public/css/jquery-ui.min.css"/> -->

	<body style="background-color:; background-image: url('<?php echo URL; ?>public/images/logo/marca2.png')">
	<div class="ui column center aligned grid" style="margin-top:40px;">
	    <div class="column" style="width:auto;">
			<img class="ui image" src="<?php echo URL; ?>public/images/logo/logo.png">
		</div>
	</div>
	<div class="ui column center aligned grid" style="margin-top:-10px; color:;">
	    <div class="column" style="width:auto;">
	    	<h1><i class="lock big icon"></i>Opa!</h1>
		</div>
	</div>

	<div class="ui column center aligned grid" style="margin-top:-25px; ">
	    <div class="column" style="width:auto;">

<div class="ui success message">
  <div class="header">
    Seu sistema está bloqueado
  </div>
  <p>Entre em contato com o nosso atendimento, e regularize sua situação.</p>
</div>

</div></div>
</body>
</html>