<?php  
	if(MODO_DESENVOLVIMENTO) { 
		header('Content-Type: application/javascript');
?>
var ATUALIZANDOBANCO = false;
function atualizarBanco(){
	if(ATUALIZANDOBANCO == false){
		alert('teste');
		colocaLoad();
		$.get("<?php echo Uteis::url(); ?>desenvolvimento/atualizar", function(retorno){
			tiraLoad();
			if(retorno !== "ok")
				alert("Ocorreu um erro durante a atualização");
			else
				alert("O banco foi atualizado com sucesso!");	
		});
	}
}

function colocaLoad(){
	ATUALIZANDOBANCO = true;
	$("#iconeDesenvolvimento").html("Atualizando... <i class='spinner loading icon'></i>");
}

function tiraLoad(){
	ATUALIZANDOBANCO = false;
	$("#iconeDesenvolvimento").html("Atualizar Banco <i class='icon refresh'></i>");
}
<?php } ?>