<div style="width:100%; text-align:center; text-transform: uppercase;">
	<h2><i class="bar chart icon"></i>Aniversariantes Visitantes</h2>

	<h3>Selecione o Mês</h3>
</div>
<a id="reciboLink" style="display:none" href="" target="_blank">teste</a> 

<form class="formulario" method="post" id="formRelatorio" target="_blank">
<div class="ui column center aligned grid">
	<div class="column" style="width: auto;">
		<div class="ui purple segment" style="width: auto;">

<input hidden name='postado' value=''>
<div class="field" id="campo_consagracao" style="margin: 2px; float:left; text-align:left;">
     <label>Mês </label><div class="ui left labeled icon input"><div class="ui search dropdown selection" id="select_consagracao" tabindex="2" onkeypress="enterSubmit(event);" onmouseover="registraSelect('select_consagracao');">
            <input type="hidden" name="mes" value="<?php echo $dados['mesValor']; ?>" id="input_consagracao" onchange=";" style="max-width:450px; min-width:300px;">
            <i class="triangle down icon disabled"></i>
            <div class="text" data-value="<?php echo $dados['mesValor']; ?>" style="max-width:450px; min-width:100px;"><?php echo $dados['mesNome']; ?></div>
              <div class="menu ui ">
                <div class="item" data-value="1">Janeiro</div>
                <div class="item" data-value="2">Fevereiro</div>
                <div class="item" data-value="3">Março</div>
                <div class="item" data-value="4">Abril</div>
                <div class="item" data-value="5">Maio</div>
                <div class="item" data-value="6">Junio</div>
                <div class="item" data-value="7">Julho</div>
                <div class="item" data-value="8">Agosto</div>
                <div class="item" data-value="9">Setembro</div>
                <div class="item" data-value="10">Outubro</div>
                <div class="item" data-value="11">Novembro</div>
                <div class="item" data-value="12">Dezembro</div>
              </div>                                     
            </div></div>
</div>
 
<br>
			<div style="width:auto; float: left; text-align:left;">
				<br>
				<div class="ui green vertical labeled icon submit button" style=" margin-right: 20px; margin: 5px; margin-top: 2px;" onclick="submtRelatorio()">
	   				<i class="checkmark icon"></i>Selecionar
	 			</div>	
	 		</div>
		</div>
	</div>
</div>
</form>	