<div style="width:100%; text-align:center; text-transform: uppercase;">
	<h2><i class="bar chart icon"></i>Relatório <br>Entradas X Saídas</h2>

	<h3>Selecione o Ano</h3>
</div>
<a id="reciboLink" style="display:none" href="" target="_blank">teste</a> 

<form class="formulario" method="post" id="formRelatorio" target="_blank">
<div class="ui column center aligned grid">
	<div class="column" style="width: auto;">
		<div class="ui purple segment" style="width: auto;">

<input hidden name='postado' value=''>

<div class="field" id="campo_ano" style="margin: 2px; float:left; text-align:left;">
     <label>Ano</label><br>
<div class="ui corner labeled left icon input"><div class="ui search dropdown selection" id="select_ano" onkeypress="enterSubmit(event);" onmouseover="registraSelect('select_ano');">
			  <?php $atual = date('y') + 2000; ?>
              <input type="hidden" name="ano" id="input_ano" value="<?php echo $atual; ?>" class="" style="max-width:150px; min-width:100px;">
              <i class="triangle down icon disabled"></i>
              <input class="search" tabindex="0">
				<div class="text" data-value=""><?php echo $atual; ?></div>
              <div class="menu ui ">
                
                <?php 
                    for($ano = 2010; $ano <= 2030; $ano++)
                        echo " <div class='item' data-value='$ano'>$ano</div>";
                 ?>
              </div>
              </div></div>
</div>  
 <br>
			<div style="width:auto; float: left; text-align:left;">
				<br>
				<div class="ui green vertical labeled icon submit button" style=" margin-right: 20px; margin: 5px; margin-top: 2px;" onclick="submtRelatorio()">
	   				<i class="checkmark icon"></i>Selecionar
	 			</div>	
	 		</div>
		</div>
	</div>
</div>
</form>	