<?php
//	header('Content-type: application/pdf');
//	header('Content-Disposition: attachment; filename="Recibo de Pagamento.pdf"');

	$caminho = RAIZ . SEPARADOR . 'views' . SEPARADOR . 'folhas' . SEPARADOR . 'pdf_recibo_class.php';
	require($caminho);

	$grafico = RAIZ . SEPARADOR . 'views' . SEPARADOR . 'relatorios' . SEPARADOR . 'grafico1.php';
	require($grafico);

	class PDF extends pdf_recibo_class
	{

		private $mes = array("", "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junio", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro");

		private $tipos = array();

		public function Header()
		{
			$this->SetTextColor(85, 85, 85);
		    $this->SetFont('Arial','I',9);
		    $this->Cell(0, -1.2,'Positv, Sistemas Inteligentes',0,0,'R');
		    $pagina = utf8_decode('Página: ');
		    $this->Cell(0, -0.5,$pagina.$this->PageNo().'/{nb}',0,0,'R');
		   	
		    $this->Ln(0);
		}

		public function Footer()
		{

		    $this->SetY(-6);
		    $this->SetFont('Arial','I',8);
		    $this->SetTextColor(85, 85, 85);
		    $dia = date('d');
		    $mes = $this->mes[date('m')/1];
		    $ano = 2000 + date('y');
		    $data = $dia.', de '.$mes.' de '.$ano;
		    $data = utf8_decode($data);
			$pagina = utf8_decode('Página: ');
		    $this->Cell(5,10, $data,0,0,'L');
		    $hora = date('G').':'.date('i').':'.date('s').' (Brasília)';
		    $hora = utf8_decode($hora);
		    $this->Cell(0,10, $hora,0,0,'L');
		    $this->Cell(0,10,$pagina.$this->PageNo().'/{nb}',0,0,'R');
		}

		public function tabela($entradas, $saidas, $ano)
		{
		    $this->SetFillColor(55, 181, 70);
		    $this->SetTextColor(255);
		    $this->SetDrawColor(53, 165, 66);
		    $this->SetLineWidth(.05);
		    $this->SetFont('','B', 10);
		    // Header

		    $tamanhosCelulas[0] = 1.1;
		    for ($i=1; $i < 13; $i++)
		    	$tamanhosCelulas[$i] = 1;

		    $tamanhosC = $this->tamanhoCelulas($tamanhosCelulas);

		    $w = array();
		    foreach ($tamanhosC as $key => $valor)
		    {
		    	$t = $valor * 0.19;
		    	array_push($w, $t);
		    }
		    
	        $this->Cell($w[0],0.7, '',1,0,'C',true);
	        $this->Cell($w[1],0.7, 'Jun',1,0,'C',true);
	        $this->Cell($w[2],0.7, 'Fev',1,0,'C',true);
	        $this->Cell($w[3],0.7, 'Marc',1,0,'C',true);
	        $this->Cell($w[4],0.7, 'Abr',1,0,'C',true);
	        $this->Cell($w[5],0.7, 'Maio',1,0,'C',true);
	        $this->Cell($w[6],0.7, 'Junh',1,0,'C',true);
	        $this->Cell($w[7],0.7, 'Julh',1,0,'C',true);
	        $this->Cell($w[8],0.7, 'Agos',1,0,'C',true);
	        $this->Cell($w[9],0.7, 'Set',1,0,'C',true);
	        $this->Cell($w[10],0.7, 'Out',1,0,'C',true);
	        $this->Cell($w[11],0.7, 'Nov',1,0,'C',true);
	        $this->Cell($w[12],0.7, 'Dez',1,0,'C',true);

		    
		    $this->Ln();

		    // Data
       		$this->Cell($w[0],0.6, 'Entradas', 100,0,'L', true);

		    $this->SetTextColor(85, 85, 85);
		    $this->SetFont('', '', 7.8);

		    $entradaTotal = 0;
		    for ($i=1; $i < 13; $i++)
		    {	
		    	$entradaTotal = $entradaTotal + $entradas[$i-1];
		    	$this->Cell($w[$i],0.6, $this->formata_moeda($entradas[$i-1]),'LR',0,'L');
		    }

  			$this->Ln();


		    $this->SetFillColor(55, 181, 70);
		    $this->SetTextColor(255);
		    $this->SetFont('','B', 10);       		

       		$this->Cell($w[0],0.6, utf8_decode('Saídas'),1,0,'R', true);

       		$this->SetFillColor(185, 234, 191);
		    $this->SetTextColor(85, 85, 85);
		    $this->SetFont('', '', 7.8);

		    $saidasTotal = 0;
		    for ($i=1; $i < 13; $i++){
		    	$saidasTotal = $saidasTotal + $saidas[$i-1];
		    	$this->Cell($w[$i],0.6, $this->formata_moeda($saidas[$i-1]),'LR',0,'L', true);
		    }

		    $this->Ln();

		    $this->Cell(array_sum($w),0,'','T');
		    $this->Ln(0.2);

		    $this->SetFillColor(55, 181, 70);
		    $this->SetTextColor(255);
		    $this->SetFont('','B', 10);       		

       		$this->Cell($w[0],0.6, 'Saldos',1,0,'R', true);

       		$this->SetFillColor(185, 234, 191);
		    $this->SetTextColor(85, 85, 85);
		    $this->SetFont('', '', 7.8);

		    for ($i=1; $i < 13; $i++)
		    {	
		    	$saldo = $entradas[$i-1] - $saidas[$i-1];
 		    	$this->Cell($w[$i],0.6, $this->formata_moeda($saldo),1,0,'L');
		    }     		

	        $this->Ln();
	        $this->Cell(array_sum($w),0,'','T');

			$this->Ln(0.8);
			$this->Cell(13,0.6,'', 0, 0,'L');
			$this->SetFillColor(55, 181, 70);
			$this->SetFont('','B', 10);
			$this->SetTextColor(255);
			$this->Cell(0,0.6,'Ano de ' . $ano,1,1,'C', true);

			$this->Cell(13,0.6,'', 0, 0,'L');
			$this->SetFillColor(55, 181, 70);
			$this->SetFont('','B', 10);
			$this->SetTextColor(255);
			$this->Cell(2,0.6,'Entrada',1,0,'R', true);

		    $this->SetTextColor(55, 181, 70);
		    $this->SetFont('', 'B', 9.5);
			$this->Cell(0,0.6, 'R$ '. $this->formata_moeda($entradaTotal),1,1,'R');

			$this->Cell(13,0.6,'', 0, 0,'L');
			$this->SetFillColor(55, 181, 70);
			$this->SetFont('','B', 10);
			$this->SetTextColor(255);
			$this->Cell(2,0.6, utf8_decode('Saída'),1,0,'R', true);

		    $this->SetTextColor(55, 181, 70);
		    $this->SetFont('', 'B', 9.5);
			$this->Cell(0,0.6, 'R$ '. $this->formata_moeda($saidasTotal),1,1,'R');	

			$this->Cell(13,0.6,'', 0, 0,'L');
			$this->SetFillColor(55, 181, 70);
			$this->SetFont('','B', 10);
			$this->SetTextColor(255);
			$this->Cell(2,0.6, 'Saldo',1,0,'R', true);

		    $this->SetTextColor(55, 181, 70);
		    $this->SetFont('', 'B', 9.5);
		    $saldo = $entradaTotal - $saidasTotal;
			$this->Cell(0,0.6, 'R$ ' . $this->formata_moeda($saldo),1,0,'R');							        		
		}

		private function tamanhoCelulas(&$celulas)
	    {
			$total = 0;
			foreach ($celulas as $key => $celula)
				$total = $total + $celula;

			$retorna;

			foreach ($celulas as $key => $celula)
				$retorna[$key] = ($celula*100)/$total;

			return $retorna;
	    }

		private function formata_moeda($valor)
		{
			$formatado = number_format($valor, 2, ',', '.');

			if(strlen($valor) > 53)
				$formatado = substr($formatado, 0, 50) . "...";

			return $formatado;
		}				
	}	

	$pdf = new PDF('P', 'cm', 'A4');	

	$pdf->Open();
	$pdf->SetMargins(1, 1, 1);
	$pdf->AliasNbPages();
	$pdf->AddPage();

	$imagem = PASTA_ARQUIVOS . 'imagens' . SEPARADOR . 'informacoes_igreja' . SEPARADOR . 'logo.png';
	$pdf->Image($imagem,1,1, null, 2.5);

	$pdf->SetTextColor(85, 85, 85);

	$pdf->SetXY(1,0.9);
	$pdf->SetFont('arial','B',12);
	$nomeIgreja = utf8_decode("Igreja Batista Ágape");
	$pdf->Cell(0, 1,$nomeIgreja, 0, 1,'C');  

	$pdf->SetFont('arial','', 12);
	$estado = utf8_decode("Sobral - CE");
	$pdf->Cell(0, 0.3,$estado, 0, 1,'C'); 	

	$pdf->SetFont('arial','', 12);
	$estado = utf8_decode("Telefone: (88) 3614-5416");
	$pdf->Cell(0, 0.6,$estado, 0, 1,'C');	

	$nomeRelatorio = utf8_decode($dados['nome']);

	$pdf->Ln(0.3);
	$pdf->SetFont('arial','B',13);
	$nomeRelatorio = utf8_decode($dados['nome']);
	$pdf->Cell(0, 1,$nomeRelatorio, 0, 1,'C'); 

	if(isset($dados['subTitulo']))
	{
		$pdf->SetFont('arial','B',11);
		$subTitulo = utf8_decode($dados['subTitulo']);
		$pdf->Cell(0, 0.5, $subTitulo, 0, 1,'C'); 
	}	

	$pdf->Ln(0.75);
	$pdf->SetFont('arial','B', 9);
	$pdf->SetDrawColor(53, 165, 66);
	$pdf->SetFillColor(0, 255, 0);
	$pdf->SetTextColor(255);
	$pdf->Cell(16, 0.6, '', 0, 0, 'C');
	$pdf->Cell(1.5, 0.6, 'Entradas', 1, 0,'C', true);

	$pdf->SetFillColor(135, 206, 235);
	$pdf->Cell(1.5, 0.6, utf8_decode('Saídas'), 1, 1,'C', true);	

	$grafico = new Grafico();
	$caminho = $grafico->criar($dados['entradas'], $dados['saidas']);
	$pdf->Image($caminho , 0.5, 6, null, null, 'PNG');
	$grafico->deletarImg();

	$pdf->Ln(9);

	$pdf->tabela($dados['entradas'], $dados['saidas'], $dados['ano']);

	$pdf->Ln(3);
	$pdf->SetFont('arial','B',11);
	$pdf->SetTextColor(85, 85, 85);
	$pdf->Cell(0, 0.1, utf8_decode('Responsável'), 0, 1, 'C');
	$pdf->Ln(0.8);
	$pdf->Cell(0, 0.1, '_____________________________', 0, 1, 'C');
	$pdf->SetFont('arial', '', 10);
	$usuario = utf8_decode($_POST['usuario']);
	$pdf->Cell(0, 0.8, $usuario, 0, 1, 'C');		

	$pdf->Output();


	function tamanhoCelulas(&$celulas)
	{
		$total = 0;
		foreach ($celulas as $celula)
			$total = $total + $celula[1];

		$retorna;

		foreach ($celulas as $key => $celula)
			$retorna[$key] = ($celula[1]*100)/$total;

		return $retorna;
	}
?>

