<div style="width:100%; text-align:center; text-transform: uppercase;">
    <h2><i class="bar chart icon"></i>Relatórios</h2>
</div>

<div class="ui column center aligned grid">
	<div class="column" style="width: auto;">

  		<table class="ui table segment" id="tabelaListagem" style="width:auto;">
  			<thead>
  				<tr>
  					<th>Relatório</th>
  					<th>Descrição</th>
  				</tr>
			</thead>
			<tbody>
				<tr>
					<td><a onclick="navegacaoSub('relatorios/','membros', '');">Membros</a></td>
					<td>Lista as informações dos Membros.</td>
				</tr>
				<tr>
					<td><a onclick="navegacaoSub('relatorios/','visitantes', '');">Visitantes</a></td>
					<td>Lista as informações dos Visitantes.</td>
				</tr>
				<tr>
					<td><a onclick="navegacaoSub('relatorios/','aniversariantesMembros', '');">Aniversariantes - Membros</a></td>
					<td>Lista os Membros que fazem aniversário no mês selecionado.</td>
				</tr>
				<tr>
					<td><a onclick="navegacaoSub('relatorios/','aniversariantesVisitantes', '');">Aniversariantes - Visitantes</a></td>
					<td>Lista os Visitantes que fazem aniversário no mês selecionado.</td>
				</tr>
				<tr>
					<td><a onclick="navegacaoSub('relatorios/','patrimonio', '');">Patrimônio</a></td>
					<td>Lista todos os bens da igreja.</td>
				</tr>
				<tr>
					<td><a>Dízimos/Ofertas</a></td>
					<td>Lista os dízimos e as ofertas no mês selecionado.</td>
				</tr>
				<tr>
					<td><a>Dízimos/Ofertas por Membro</a></td>
					<td>Lista os dízimos e as ofertas de um determinado Membro.</td>
				</tr>
				<tr>
					<td><a>Contas a Pargar</a></td>
					<td>Lista as contas a pagar no mês selecionado.</td>
				</tr>
				<tr>
					<td><a>Contas a Receber</a></td>
					<td>Lista as contas a receber no mês selecionado.</td>
				</tr>
				<tr>
					<td><a>Entradas X Saídas</a></td>
					<td>Comparativo das Entradas e Saídas.</td>
				</tr>
				<tr>
					<td><a>Entradas por Categorias</a></td>
					<td>Lista as Entradas pelas Categorias.</td>
				</tr>
				<tr>
					<td><a>Saídas por Categorias</a></td>
					<td>Lista as Saídas pelas Categorias.</td>
				</tr>
				<tr>
					<td><a onclick="navegacaoSub('relatorios/','programacoes', '');">Programações</a></td>
					<td>Lista todos os eventos no mês selecionado.</td>
				</tr>
				<tr>
					<td><a onclick="navegacaoSub('relatorios/','folhas_de_pagamentos', '');">Folhas de Pagamentos</a></td>
					<td>Lista informações das folhas de pagamentos.</td>
				</tr>
				<tr>
					<td><a>Pagamentos por Funcionários</td>
					<td>Lista os pegamentos de um determinado funcionário.</td>
				</tr>
				<tr>
					<td><a onclick="navegacaoSub('relatorios/','funcionarios', '');">Funcionários</a></td>
					<td>Lista as informações dos funcionários.</td>
				</tr>
			</tbody>  
		</table>	

	</div>
</div>