<div style="width:100%; text-align:center; text-transform: uppercase;">
    <h2><i class="bar chart icon"></i>Relatórios</h2>
</div>

<div class="ui column center aligned grid">
	<div class="column" style="width: auto;">

  		<table class="ui table segment" id="tabelaListagem" style="width:auto;">
  			<thead>
  				<tr>
  					<th>Relatório</th>
  					<th>Descrição</th>
  				</tr>
			</thead>
			<tbody>
				<tr>
					<td><a onclick="navegacaoSub('relatorios/','membros', '');"><i class="circular teal inverted small university icon"></i>Membros</a></td>
					<td>Lista as informações dos Membros.</td>
				</tr>
				<tr>
					<td><a onclick="navegacaoSub('relatorios/','visitantes', '');"><i class="circular teal inverted small university icon"></i>Visitantes</a></td>
					<td>Lista as informações dos Visitantes.</td>
				</tr>
				<tr>
					<td><a onclick="navegacaoSub('relatorios/','aniversariantesMembros', '');"><i class="circular teal inverted small university icon"></i>Aniversariantes - Membros</a></td>
					<td>Lista os Membros que fazem aniversário no mês selecionado.</td>
				</tr>
				<tr>
					<td><a onclick="navegacaoSub('relatorios/','aniversariantesVisitantes', '');"><i class="circular teal inverted small university icon"></i>Aniversariantes - Visitantes</a></td>
					<td>Lista os Visitantes que fazem aniversário no mês selecionado.</td>
				</tr>
				<tr>
					<td><a onclick="navegacaoSub('relatorios/','patrimonio', '');"><i class="circular red inverted small suitcase icon"></i>Patrimônio</a></td>
					<td>Lista todos os bens da igreja.</td>
				</tr>
				<tr>
					<td><a onclick="navegacaoSub('relatorios/','dizimosOfertas', '');"><i class="circular orange inverted small dollar icon"></i>Dízimos/Ofertas</a></td>
					<td>Lista os dízimos e as ofertas no mês selecionado.</td>
				</tr>
				<tr>
					<td><a onclick="navegacaoSub('relatorios/','dizimos_ofertas_membro', '');"><i class="circular orange inverted small dollar icon"></i>Dízimos/Ofertas por Membro</a></td>
					<td>Lista os dízimos e as ofertas de um determinado Membro.</td>
				</tr>
				<tr>
					<td><a href="<?php echo URL; ?>relatorios/contas_a_pagar" target="_blank" onclick="function(event){ return true; }"><i class="circular orange inverted small dollar icon"></i>Contas a Pargar</a></td>
					<td>Lista todas as contas a pagar.</td>
				</tr>
				<tr>
					<td><a href="<?php echo URL; ?>relatorios/contas_a_receber" target="_blank" onclick="function(event){ return true; }"><i class="circular orange inverted small dollar icon"></i>Contas a Receber</a></td>
					<td>Lista todas as contas a receber.</td>
				</tr>
				<tr>
					<td><a onclick="navegacaoSub('relatorios/','entradasXsaidas', '');"><i class="circular orange inverted small dollar icon"></i>Entradas X Saídas</a></td>
					<td>Comparativo das Entradas e Saídas.</td>
				</tr>
				<tr>
					<td><a onclick="navegacaoSub('relatorios/','entradas_por_categoria', '');"><i class="circular orange inverted small dollar icon"></i>Entradas por Categorias</a></td>
					<td>Lista as Entradas pelas Categorias.</td>
				</tr>
				<tr>
					<td><a onclick="navegacaoSub('relatorios/','saidas_por_categoria', '');"><i class="circular orange inverted small dollar icon"></i>Saídas por Categorias</a></td>
					<td>Lista as Saídas pelas Categorias.</td>
				</tr>
				<tr>
					<td><a onclick="navegacaoSub('relatorios/','programacoes', '');"><i class="circular blue inverted small calendar icon"></i>Programações</a></td>
					<td>Lista todos os eventos no mês selecionado.</td>
				</tr>
				<tr>
					<td><a onclick="navegacaoSub('relatorios/','folhas_de_pagamentos', '');">
						<img class="circular ui inverted image" style="width:28px; height:14; float:left;" src="<?php echo URL; ?>public/images/icons/funcionario.png">
						<div style="margin-top:5px;">Folhas de Pagamentos</div></a></td>
					<td>Lista informações das folhas de pagamentos.</td>
				</tr>
				<tr>
					<td><a onclick="navegacaoSub('relatorios/','pagamentos_por_funcionario', '');">
						<img class="circular ui inverted image" style="width:28px; height:14; float:left;" src="<?php echo URL; ?>public/images/icons/funcionario.png">
						<div style="margin-top:5px;">Pagamentos por Funcionário</div></a></td>
					<td>Lista os pegamentos de um determinado funcionário.</td>
				</tr>
				<tr>
					<td><a onclick="navegacaoSub('relatorios/','funcionarios', '');">
						<img class="circular ui inverted image" style="width:28px; height:14; float:left;" src="<?php echo URL; ?>public/images/icons/funcionario.png">
						<div style="margin-top:5px;">Funcionários</div></a></td>
					<td>Lista as informações dos funcionários.</td>
				</tr>
			</tbody>  
		</table>	

	</div>
</div>