<div style="width:100%; text-align:center; text-transform: uppercase;">
	<h2><i class="bar chart icon"></i>Relatório <br>Pagamentos por Funcionário</h2>

	<h3>Selecione o funcionário</h3>
</div>
<a id="reciboLink" style="display:none" href="" target="_blank">teste</a> 

<form class="formulario" method="post" id="formRelatorio" target="_blank">
<div class="ui column center aligned grid">
	<div class="column" style="width: auto;">
		<div class="ui purple segment" style="width: auto;">

<input hidden name='postado' value=''>
<div class="field" id="campo_funcionario" style="margin: 2px; float:left; text-align:left;">
     <label>Funcionário </label><div class="ui left labeled icon input"><div class="ui search dropdown selection" id="select_funcionario" tabindex="2" onkeypress="enterSubmit(event);" onmouseover="registraSelect('select_funcionario');">
            <input type="hidden" name="funcionario" id="input_funcionario" style="max-width:450px; min-width:300px;">
            <i class="triangle down icon disabled"></i>
            <div class="text" data-value="" style="max-width:450px; min-width:200px;"></div>
              <div class="menu ui ">
                <div class="item" data-value=""></div>
                <?php 
                 foreach ($dados as $campo)
                    echo "<div class='item' data-value='". $campo['id'] ."'>". $campo['nome'] ."</div>";
                ?>
              </div>                                     
            </div></div>
</div>	
			<div style="width:auto; float: left; text-align:left;">
				<br>
				<div class="ui green vertical labeled icon submit button" style=" margin-right: 20px; margin: 5px; margin-top: 2px;" onclick="submtRelatPagamFunc();">
	   				<i class="checkmark icon"></i>Selecionar
	 			</div>	
	 		</div>
		</div>
	</div>
</div>
</form>	