<div style="width:100%; text-align:center; text-transform: uppercase;">
	<h2><i class="bar chart icon"></i>Relatório <br>Saídas por Categoria</h2>

	<h3>Selecione os filtros</h3>
</div>

<form class="formulario" method="post" id="formRelatorio" target="_blank">
<div class="ui column center aligned grid">
	<div class="column" style="width: auto;">
		<div class="ui purple segment" style="width: auto;">

<input hidden name='postado' value=''>
<div class="field" id="campo_categoria" style="margin: 2px; float:left; text-align:left;">
     <label>Categoria </label><div class="ui left labeled icon input"><div class="ui search dropdown selection" id="select_categoria" tabindex="2" onkeypress="enterSubmit(event);" onmouseover="registraSelect('select_categoria');">
            <input type="hidden" name="categoria" id="input_categoria" class="" onchange="" value="" style="max-width:450px; min-width:300px;">
            <i class="triangle down icon disabled"></i>
            <div class="text" data-value="" style="max-width:450px; min-width:210px;"></div>
              <div class="menu ui ">
                <div class="item" data-value=""></div>
                <?php
                	foreach ($dados as $cargo)
                		echo "<div class='item' data-value='".$cargo['id']."'>".$cargo['nome']."</div>";
                ?>
              </div>                                     
            </div></div>
</div>	

<div class="field" id="campo_pagamento" style="margin: 2px; float:left; text-align:left;">
     <label>Pagamento</label><br>
<div class="ui corner labeled left icon input"><div class="ui search dropdown selection" id="select_pagamento" onkeypress="enterSubmit(event);" onmouseover="registraSelect('select_pagamento');">
              <input type="hidden" name="pagamento" id="input_pagamento" class="" onchange="validar('pagamento');" style="max-width:150px; min-width:100px;">
              <i class="triangle down icon disabled"></i>
              <input class="search" tabindex="0"><div class="text" data-value="" style="max-width:100px; min-width:100px;"></div>
              <div class="menu transition hidden" tabindex="-1" style="">
                <div class="item active selected" data-value=""></div>
                <div class="item" data-value="1">Efetuado</div>
                <div class="item" data-value="2">Não Efetuado</div>
              </div>
              </div></div>
</div> 

<div style="margin-top: 0px;"> <label>Período de</label> </div>

<div class='ui left corner labeled icon input'>
  <input type='text' class='' tabindex="2" onkeypress="enterSubmit(event);" style='width:300px; margin-top:2px;' value='' id='input_inicio' placeholder='__/__/____' name='inicio' onfocus="datapick('input_inicio');"><i class='empty calendar icon'></i>
  </div>
  <br>
   <labe>a</label>
  <br>
<div class='ui left corner labeled icon input'><input type='text' class='' tabindex="2" onkeypress="enterSubmit(event);" style='width:300px; margin-top:2px;' value='' id='input_fim' placeholder='__/__/____' name='fim' onfocus="datapick('input_fim');"><i class='empty calendar icon'></i></div>

<br>
  		<div style="width:auto; float: left; text-align:left;">
				<br>
				<div class="ui green vertical labeled icon submit button" style=" margin-right: 20px; margin: 5px; margin-top: 2px;" onclick="submtRelatSaidEntCateg()">
	   				<i class="checkmark icon"></i>Selecionar
	 			</div>	
	 		</div>
		</div>
	</div>
</div>
</form>	