</div>
</div>
</div>


<div class="ui small modal canfirmar">
  <i class="close icon"></i>
  <div class="header">
    Confirmação
  </div>
  <div class="content" id="msgConfirmacao">
  </div>
  <div class="actions">
    <div class="ui positive labled icon button">
      <i class="ui thumbs up icon"></i>
      Sim
    </div>    
    <div class="ui negative labled icon button">
      <i class="ui thumbs down icon"></i>
      Não
    </div>
  </div>
</div>

<div class="ui small modal sucesso">
  <i class="close icon"></i>
  <div class="header">
    Tudo Ok!
  </div>
  <div class="content" id="msgAlerta">
  </div>
  <div class="actions">
    <div class="ui positive labled icon button">
      <i class="ui thumbs up icon"></i>
      OK
    </div>    
  </div>
</div>

<div class="ui small modal erro">
  <i class="close icon"></i>
  <div class="header">
    Opa!
  </div>
  <div class="content" id="msgAlertaErro">
  </div>
  <div class="actions">
    <div class="ui labled icon button">
      <i class="ui thumbs up icon"></i>
      OK
    </div>    
  </div>
</div>

<br><br>

<div class="ui inverted black footer vertical segment">
  <div class="container">
    <div class="ui stackable inverted divided relaxed grid">
      <div class="eight wide column">
        <h3 class="ui inverted header"><i class="cloud icon" style='margin-bottom:0px;'></i>Positiv Sistemas</h3>
        <p>Simples, Seguro e Inteligente</p>
      </div>
      <div class="four wide column">
        <h5 class="ui teal inverted header">Contribute</h5>
        <div class="ui inverted link list">
          <a class="item" href="https://www.transifex.com/organization/semantic-org/" target="_blank">Centro de tradução</a>
          <a class="item" href="https://github.com/Semantic-Org/Semantic-UI" target="_blank">Issue Tracker</a>
          <a class="item" href="/cla.html" target="_blank">CLA</a>
          <a class="disabled item">Criar Temas</a>
        </div>
      </div>
    </div>
  </div>
</div>

 </div>
</body>
</html>