<div style="width:100%; text-align:center;">
	<div class="mini ui labeled icon button balao" onclick="navegacaoSub('informacoes/','', '');">
		<i class="info icon"></i>INFORMAÇÕES DA IGREJA
	</div>
</div>
<br>
<div style="width: 400px; float:left;">
  <canvas id="canvas" height="450" width="600"></canvas>
</div>

<div id="canvas-holder" style="width: 300px; float:left;">
  <canvas id="chart-area" width="500px" height="500px"/>
</div>

<div style="width:30%; float:left;">
  <div>
    <canvas id="canvas3" height="450" width="600"></canvas>
  </div>
</div>

<div id="canvas-holder">
  <canvas id="chart-area4" width="300" height="300"/>
</div>