<?php
  $mes = array("", "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junio", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro");
?>
<div style="width:100%; text-align:center; text-transform: uppercase;">
	<h2><i class="file powerpoint outline icon"></i>Editar Folha</h2>
	<h3><?php echo $mes[$dados['folha']['mes']]. " de " .$dados['folha']['ano']. "<br> Total: R$ ".$dados['folha']['total']; ?></h3>
</div>

<form class="formulario">
<div class="ui column center aligned grid">
	<div class="column" style="width: auto;">
		<div class="ui segment" style="width: auto;">

<input hidden id='idFolha' value='<?php echo $dados['idFolha']; ?>'>
<div class="field" id="campo_funcionario" style="margin: 2px; float:left; text-align:left;">
     <label>Funcionário </label><div class="ui left labeled icon input"><div class="ui search dropdown selection" id="select_funcionario" tabindex="2" onkeypress="enterSubmit(event);" onmouseover="registraSelect('select_funcionario');">
            <input type="hidden" name="mes" id="input_funcionario" class="" onchange="" style="max-width:450px; min-width:300px;">
            <i class="triangle down icon disabled"></i>
            <div class="text" data-value="" style="max-width:450px; min-width:100px;"></div>
              <div class="menu ui ">
                <div class="item" data-value=""></div>
                <div class="item" data-value="-1">Todos</div>
                <?php
                	foreach ($dados['funcs'] as $key => $campos)
                		echo "<div class='item' data-value='".$campos['id']."'>".$campos['nome']."</div>";
                ?>
              </div>                                     
            </div></div>
</div>		
			<div style="width:auto; float: left; text-align:left;">
				<br>
				<div class="ui green vertical labeled icon submit button" style=" margin-right: 20px; margin: 5px; margin-top: 2px;" onclick="selecionarFunc();">
	   				<i class="checkmark icon"></i>Selecionar
	 			</div>	
	 		</div>
		</div>
	</div>
</div>
</form>	