<?php

//	header('Content-type: application/pdf');
//	header('Content-Disposition: attachment; filename="Folha de Pagamento.pdf"');

	$this->html->pdf();

	class PDF extends FPDF{

		private $mes = array("", "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junio", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro");

		function Header(){

		    $this->SetFont('Arial','I',9);
		    $this->Cell(0, -1.2,'Positv, Sistemas Inteligentes',0,0,'R');
		    $pagina = utf8_decode('Página: ');
		    $this->Cell(0, -0.5,$pagina.$this->PageNo().'/{nb}',0,0,'R');
		   	
		    $this->Ln(0);
		}

		function Footer(){

		    $this->SetY(-6);
		    $this->SetFont('Arial','I',8);

		    $dia = date('d');
		    $mes = $this->mes[date('m')/1];
		    $ano = 2000 + date('y');
		    $data = $dia.', de '.$mes.' de '.$ano;
		    $data = utf8_decode($data);
			$pagina = utf8_decode('Página: ');
		    $this->Cell(5,10, $data,0,0,'L');
		    $hora = date('G').':'.date('i').':'.date('s').' (Brasília)';
		    $hora = utf8_decode($hora);
		    $this->Cell(0,10, $hora,0,0,'L');
		    $this->Cell(0,10,$pagina.$this->PageNo().'/{nb}',0,0,'R');
		}
	}	

	$pdf = new PDF('P', 'cm', 'A4');

	$pdf->Open();
	$pdf->SetMargins(1, 1.8, 1);
	$pdf->AliasNbPages();
	$pdf->AddPage();


	$pdf->SetFont('arial','B',15);
	$pdf->Cell(0,0,"Folha de Pagamento",0,1,'L');
	$pdf->Ln(0.4);
	$pdf->SetFont('arial','',9);

	$igreja = "Estabelecimento: ". strtoupper('Igreja Batista Ágape') ." - CNPJ: 02.324.596/0001-25";
	$igreja = utf8_decode($igreja);

	$mes = ($dados['folha']['mes'] < 10) ? "0".$dados['folha']['mes'] : $dados['folha']['mes'];
	$mesano = "Mês/Ano: ".$mes."/".$dados['folha']['ano'];
	$mesano = utf8_decode($mesano);

	$emissao = "Emissão: 19/12/2014";
	$emissao =  utf8_decode($emissao);

	$pdf->Cell(0,0.4, $igreja,0,1,'L');
	$pdf->Cell(0,0.4, $mesano,0,1,'L');
	$pdf->Cell(0,0.4, $emissao,0,1,'L');

	$pdf->Cell(0,0.2,"","B",1,'C');
	$pdf->Ln(0.2);
	$pdf->SetFont('arial','B',9);
	$pdf->Cell(8, 0.1, 'Empregado', 0, 0, 'L');
	$pdf->Cell(7, 0.1, 'Evento', 0, 0, 'L');
	$pdf->Cell(2, 0.1, 'Proventos', 0, 0, 'L');
	$pdf->Cell(2, 0.1, 'Descontos', 0, 1, 'L');

	$pdf->Cell(0,0.2,"","B",1,'C');

	$pdf->SetFont('arial','',9);

	foreach ($dados['funcionarios'] as $key => $campos)
		funcionario($pdf, $campos, $dados);

	$pdf->Ln(1.9);
	$pdf->SetFont('arial','B',11);
	$pdf->Cell(0, 0.1, utf8_decode('Responsável'), 0, 1, 'C');
	$pdf->Ln(0.8);
	$pdf->Cell(0, 0.1, '_____________________________', 0, 1, 'C');
	$pdf->SetFont('arial', '', 10);
	$pdf->Cell(0, 0.8, utf8_decode('João Alisson'), 0, 1, 'C');

	$pdf->Output();	


	function funcionario($pdf, &$funcionario, &$dados){

		$eventos = isset($dados['eventos'][$funcionario['id']]) ? $dados['eventos'][$funcionario['id']] : array();

		$eventosTodos = $dados['eventosTodos'];

		$eventos = array_merge($eventos, $eventosTodos);

		$pdf->Ln(0.1);
		$nome = $funcionario['nome'];
		$nome = strtoupper($nome);
		$nome = utf8_decode($nome);

		$cargo = $funcionario['cargo'];
		$cargo = strtoupper($cargo);
		$cargo = utf8_decode($cargo);

		$cpfRg = '';
		if($funcionario['rg'] != '')
			$cpfRg = 'RG: '.$funcionario['rg'];

		if($funcionario['cpf'] != '')
			$cpfRg = 'CPF: '.$funcionario['cpf'];		

		$pdf->Cell(2, 0.4, $nome, 0, 1, 'L');
		if($cpfRg != "")
			$pdf->Cell(2, 0.4, $cpfRg, 0, 1, 'L');
		$pdf->Cell(2, 0.4, 'Cargo: '.$cargo, 0, 1, 'L');

		$salarioB = 'Salário-Base';
		$salarioB = utf8_decode($salarioB);
		$pdf->Cell(8, 0, '', 0, 0, 'L');
		$pdf->Cell(7, 0.4, $salarioB, 0, 0, 'L');
		$pdf->Cell(2, 0.4, formataMoeda($funcionario['salario']), '0', 1, 'L');

		$totalProventos = $funcionario['salario'];
		$totalDescontos = $funcionario['inss'];

		if($funcionario['inss'] != 0){
			$sub = empty($eventos) ? 'B' : 0;
			$pdf->Cell(8, 0, '', 0, 0, 'L');
			$taixa = retornaTaxa($funcionario['salario'], $dados['tabelaInss']);
			$taixa .= "%";
			$inss = "INSS ($taixa)";
			$pdf->Cell(7, 0.4, $inss, 0, 0, 'L');
			$pdf->Cell(2, 0.4, '', $sub, 0, 'L');
			$pdf->Cell(2, 0.4, formataMoeda($funcionario['inss']), $sub, 1, 'L');
		}

		foreach ($eventos as $key => $campo) {
			$abon = "";
			$descont = "";
			if($campo['tipo'] == 1){
				$abon = formataMoeda($campo['valor']);
				$totalProventos = $totalProventos + $campo['valor'];
			}else{
				$descont = formataMoeda($campo['valor']);
				$totalDescontos = $totalDescontos + $campo['valor'];
			}
			$sub = 0;
			if(end($eventos) == $campo)
				$sub = "B";
			$pdf->Cell(8, 0, '', 0, 0, 'L');
			$pdf->Cell(7, 0.4, $campo['descricao'], 0, 0, 'L');
			$pdf->Cell(2, 0.4, $abon, $sub, 0, 'L');
			$pdf->Cell(2, 0.4, $descont, $sub, 1, 'L');			
		}
		//somas
		$pdf->Cell(15, 0.5, '', 0, 0, 'L');
		$pdf->Cell(2, 0.5, formataMoeda($totalProventos), 0, 0, 'L');
		$pdf->Cell(2, 0.5, formataMoeda($totalDescontos), 0, 1, 'L');

		$total = $totalProventos - $totalDescontos;
		$total = formataMoeda($total);
		$pdf->Cell(14, 0.5, '', 0, 0, 'L');
		$pdf->Cell(3, 0.5, 'Total a receber:', 0, 0, 'L');
		$pdf->Cell(2, 0.5, $total, 0, 1, 'L');

		$pdf->Ln(0.3);
		$pdf->Cell(7, 0.5, 'Data: ', 0, 0, 'R');
		$pdf->Cell(3, 0.5, '      /        /    ', 'B', 0, 'L');

		$pdf->Cell(2, 0.5, 'Assinatura: ', 0, 0, 'R');
		$pdf->Cell(7, 0.5, '', 'B', 1, 'L');

		$pdf->Ln(0.3);
		$pdf->Cell(0,0.2,"","B",1,'C');		
	}

	function formataMoeda($valor){
		return number_format($valor, 2, ',', '.');
	}

	function retornaTaxa($valor, $tabela){

		if($valor < $tabela[0]['fim']){
			return $tabela[0]['taxa'];
		}else{
			if($valor < $tabela[1]['fim'])
				return $tabela[1]['taxa'];
			else
				return $tabela[2]['taxa'];
		}
	}	
?>
