<?php 
	if(isset($dados['retorno'])){
			$retornoJson['valido'] = $dados['retorno'][0];
			$retornoJson['mensagem'] = $dados['retorno'][1];
			$retornoJson['erros'] = isset($dados['retorno'][2]) ? $dados['retorno'][2] : "";

			$retornoJson = json_encode($retornoJson);
			echo $retornoJson;

	}else{
?>
<style>
@media (min-width: 460px) {
  .divForm {
    width:450px !important;
  }
}
</style>

<?php
	$html2->formulario('nMembro');
	$quantidade = count($dados['campos']);
	echo "<input hidden name='subNaoMembro'>
		  <div class=\"column\" style=\"width:auto;\">
		  	<div class=\"ui left aligned segment\" style=\"\">";

		  	inicio();

			$html2->campo("nome");		  		
			$this->html->campo("cargo", true, null, null, "cargo2");
			$this->html->campo("salario", true, null, null, "salario2");
		 	//$this->html->campo("situacao", true, null, null, "situacao2");
     		
     		echo "<div class='field' id='campo_situacao2'>
  				 <label>Situação</label><div class='ui corner labeled left icon input'><div class='ui search dropdown selection' id='select_situacao2' onkeypress=\"enterSubmit(event);\" onmouseover=\"registraSelect('select_situacao2');\">
             	 <input type='hidden' name='situacao2' id='input_situacao2' class='validarObrigatorio' onchange=\"validar('situacao2');mostrarDtDemissao('2')\" style='max-width:450px; min-width:300px;''>
           		   <i class='triangle down icon disabled'></i>
         		 <input class='search' tabindex='0'><div class='text' data-value='' style='max-width:450px; min-width:300px;'></div>
           		  <div class='menu transition hidden' tabindex='-1' style=''><div class='item active selected' data-value=''></div><div class='item' data-value='Ativo'>Ativo</div><div class='item' data-value='De Ferias'>De Férias</div><div class='item' data-value='Demitido'>Demitido</div>
            	 </div><div class='ui corner label'><i class='icon asterisk'></i></div>
              	</div></div></div>";			
			echo "<div id='demissaoId2' style='display:none'>";
				$this->html->campo("demissao",  true, null, null, "demissao2");
			echo "</div>";

			fim();
			inicio();

			echo "<br><script type=\"text/javascript\">$(document).ready(function(){ $('.ui.checkbox').checkbox(); });</script>
				<div class='ui checkbox'>
				<input name='inss' type='checkbox'>
				<label><strong>Calcular INSS</strong></label>
				</div><br><br>";		  

			$this->html->campo("admissao", true, null, null, "admissao2");
		  	$this->html->campo("descricao");

	echo "</div></div><br>";

	if($quantidade <= 6)
		echo "<div class=\"column divForm\" style=\"width:auto; max-width: 450px;\">
				<div class=\"ui left aligned segment\" style=\"\">";
	else
		echo "<div class=\"column\" style=\"width:auto;\">
				<div class=\"ui left aligned segment\" style=\"\">";
	
	
	if($quantidade > 6)
		inicio();
	
	$metade = (int)($quantidade/2) + 1;
	$ultimo = $quantidade - 1;

	$cont = 0;

	foreach ($dados['campos'] as $chave => $campo) {
		if($campo != "nome"){
			$html2->campo($chave);
			$cont++;
			if($cont == $metade && $quantidade > 6){
				fim();
				inicio();
			}	
		}
	}
	
	if($quantidade > 6)
		fim();

	echo "<div style='clear: both;'>";
	$this->html->submeter(null , "cadastrar/ab:2", null, null, null, "nMembro"); 
	echo "</div>";
	fim();
	echo "</div>";
		$this->html->formularioFim(); 
}?>
