<div style="width:100%; text-align:center; text-transform: uppercase;">
    <h2><i class="file icon"></i>Documento</h2>
    <h3>Apresentação de Criança</h3>
</div>
<script type="text/javascript">
  function submeterApresentacao(){
      mensagemErro = '';
      iconeErro = '<i class=\'warning icon\'></i>';
      if($("#input_crianca").val() == "")
        mensagemErro = iconeErro + 'Informe o nome da Criança.';

      if($("#input_sexo").val() == "")
        if(mensagemErro != '')
          mensagemErro = mensagemErro + '<br>' + iconeErro + 'Informe o sexo da Criança.';
        else
          mensagemErro = iconeErro + 'Informe o sexo da Criança.';       

      if($("#input_nascimento").val() == "")
        if(mensagemErro != '')
          mensagemErro = mensagemErro + '<br>' + iconeErro + 'Informe a data de nascimento.';
        else
          mensagemErro = iconeErro + 'Informe a data de nascimento.';           

      if($("#input_pai").val() == "")
        if(mensagemErro != '')
          mensagemErro = mensagemErro + '<br>' + iconeErro + 'Informe o nome do Pai.';
        else
          mensagemErro = iconeErro + 'informe o nome do Pai.';

      if($("#input_mae").val() == "")
        if(mensagemErro != '')
          mensagemErro = mensagemErro + '<br>' + iconeErro + 'Informe o nome da Mãe.';
        else
          mensagemErro = iconeErro + 'Informe o nome da Mãe.';               
      
      if(mensagemErro == '')
        $("#formRelatorio").submit();
      else
        erroCertificado_curso(mensagemErro);
  }
</script>
<form class="formulario" method="post" id="formRelatorio" target="_blank">
<div class="ui column center aligned grid">
	<div class="column" style="width: auto;">
		<div class="ui purple segment" style="width: auto;">

<input hidden name='postado' value=''>
<div class="field" id="campo_crianca" style="margin: 2px; float:left; text-align:left;">
<label>Nome da Criança</label><br>
<div class="ui corner labeled left icon input">
    <input type="text" class="obrigatorio nome" value="" onkeypress="enterSubmit(event);" style="max-width:450px; min-width:300px;" id="input_crianca" placeholder="" name="crianca" onkeyup="; limpaNome('nome');" onblur=""><i class="child icon"></i> <div class="ui corner label"><i class="icon asterisk"></i></div>
</div>
</div>
<br>

<div class="field" id="campo_sexo" style="margin: 2px; float:left; text-align:left;">
       <label>Sexo da Criança</label><br><div class="ui corner labeled left icon input"> <div class="ui search dropdown selection" id="select_sexo" onkeypress="enterSubmit(event);" onmouseover="registraSelect('select_sexo');">
              <input type="hidden" name="sexo" id="input_sexo" class="validarObrigatorio" style="min-width:50px;" onchange="validar('sexo'); trocaImgSexo('sexo');">
              <i class="male icon disabled" id="masculino_sexo"></i><i class="female icon disabled" id="feminino_sexo"></i>
              <input class="search" tabindex="0"><div class="text" style="min-width:50px;" data-value=""></div>
              <i class="dropdown icon"></i>
              <div class="menu transition hidden" tabindex="-1" style="">
              <div class="item active selected" data-value=""></div>
                <div class="item" data-value="1"><i class="male icon"></i>Masculino</div>
                <div class="item" data-value="2"><i class="female icon"></i>Feminino</div>
              </div><div class="ui corner label"><i class="icon asterisk"></i></div>
              </div></div></div>

<br>

<div class="field" id="campo_nascimento" style="margin: 2px; float:left; text-align:left;">
<label>Data de Nascimento</label><br>
<div class="ui corner labeled left icon input">
    <input type="text" class="obrigatorio" value="" onfocus="datapick('input_nascimento');" onkeypress="enterSubmit(event);" style="max-width:450px; min-width:300px;" id="input_nascimento" placeholder="" name="nascimento" onkeyup="; limpaNome('nome');" onblur=""><i class="empty calendar icon"></i>
    <div class="ui corner label"><i class="icon asterisk"></i></div>
</div>
</div>

<br>
<div class="field" id="campo_pai" style="margin: 2px; float:left; text-align:left;">
<label>Nome do Pai</label><br>
<div class="ui corner labeled left icon input">
    <input type="text" class="obrigatorio nome" value="" onkeypress="enterSubmit(event);" style="max-width:450px; min-width:300px;" id="input_pai" placeholder="" name="pai" onkeyup="; limpaNome('nome');" onblur=""><i class="male icon"></i> <div class="ui corner label"><i class="icon asterisk"></i></div>
</div>
</div>
<br>

<div class="field" id="campo_mae" style="margin: 2px; float:left; text-align:left;">
<label>Nome da Mãe</label><br>
<div class="ui corner labeled left icon input">
    <input type="text" class="obrigatorio nome" value="" onkeypress="enterSubmit(event);" style="max-width:450px; min-width:300px;" id="input_mae" placeholder="" name="mae" onkeyup="; limpaNome('nome');" onblur=""><i class="female icon"></i> <div class="ui corner label"><i class="icon asterisk"></i></div>
</div>
</div>


<br>

			<div style="width:auto; float: left; text-align:left;">
				<br>
				<div class="ui green vertical labeled icon submit button" style=" margin-right: 20px; margin: 5px; margin-top: 2px;" onclick="submeterApresentacao();">
	   				<i class="checkmark icon"></i>Gerar Certificado
	 			</div>	
	 		</div>
		</div>
	</div>
</div>
</form>	