<?php
	require(RAIZ . SEPARADOR . 'views' . SEPARADOR . 'documentos' . SEPARADOR . 'htmlPdf.php');
	header('Content-type: application/pdf');
	header('Content-Disposition: attachment; filename="Recibo de Pagamento.pdf"');

	$pdf = new PDF_HTML('L', 'cm', 'A4');	

	$pdf->Open();
	$pdf->SetMargins(6, 6, 6);
	$pdf->AddPage();

	$IGREJA = $_POST['nomeIgreja'];

	$imagem = PASTA_SISTEMA . 'imagens' . SEPARADOR . 'moldura.jpg';
	$pdf->Image($imagem, 0, 0, null, 21);

	$imagem = PASTA_ARQUIVOS . 'imagens' . SEPARADOR . 'informacoes' . SEPARADOR . 'logo.png';
	if(file_exists($imagem))
		$pdf->Image($imagem, 4, 4.2, null, 2);

	$pdf->AddFont('CrimsonText-Regular','','CrimsonText-Regular.php');
	$pdf->AddFont('CrimsonText-Regular','B','CrimsonText-Bold.php');
	$pdf->AddFont('CrimsonText-Regular','I','CrimsonText-Italic.php');
	$pdf->AddFont('CrimsonText-SemiboldItalic','','CrimsonText-SemiboldItalic.php');

	$mesArray = array("", "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junio", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro");
	$dia = date('d');
	$mes = $mesArray[date('m')/1];
	$ano = date('y') + 2000;

	$data = $dia . ' de ' . $mes . ', ' . $ano;
	$data = utf8_decode($data);

	$pdf->SetFont('CrimsonText-Regular','', 25);
	$pdf->SetTextColor(133, 166, 175);
	$pdf->Cell( null, 1, "Certificado de Membro", 0, 1,'C');
	
	$pdf->SetFont('CrimsonText-SemiboldItalic','', 29);
	$pdf->SetTextColor(80, 113, 128);
	$pdf->Cell( null, 1.2, 'Igreja ' . utf8_decode($IGREJA), 0, 0,'C');   

	$pdf->SetFont('CrimsonText-Regular','', 14);

	$text = "<p>          Certificamos que <strong>". $dados ."</strong> faz parte do hall de membros da Igreja " . $IGREJA. ", bem como do corpo de Cristo.<br><br>\"<i>Ora, vós sois o corpo de Cristo, e seus membros em particular.</i>\"

1 Coríntios 12:27</p>";
	$text = utf8_decode($text);
	$pdf->Ln(-6.7);
	$pdf->WriteHTML($text);

	$pdf->SetXY(6, 15.5);
	$pdf->SetFont('arial','B',16);
	$pdf->Cell( null, 0.5, '_________________', 0, 1,'L');   
	$pdf->SetFont('CrimsonText-SemiboldItalic', '', 11);
	$pdf->Cell(2, 0.5, '                     Pastor', 0, 0, 'L');

	$pdf->SetXY(18, 15.5);
	$pdf->SetFont('arial','B',16);
	$pdf->Cell( null, 0.5, '_________________', 0, 1,'L');   
	$pdf->SetFont('CrimsonText-SemiboldItalic', '', 11);
	$pdf->SetXY(20, 16);
	$pdf->Cell(null, 0.5, 'Membro', 0, 1, 'L');	


	$pdf->SetXY(21.5, 5.5);
	$pdf->SetFont('CrimsonText-Regular','I', 12);
	$pdf->Cell( null, 1, $data, 0, 1,'L');		

	$pdf->Output();
?>

