<div style="width:100%; text-align:center; text-transform: uppercase;">
    <h2><i class="file icon"></i>Documentos</h2>
</div>
<?php $cor = 'blue'; ?>
<div class="ui column center aligned grid">
	<div class="column" style="width: auto;">
		
  		<table class="ui table segment" id="tabelaListagem" style="width:auto;">
			<tbody>
				<tr>
					<td><a href="<?php echo Uteis::url(); ?>documentos/informacoes" target="_blank"><i class="circular <?php echo $cor; ?> university icon"></i>Informações da Igreja</a></td>
				</tr>				
				<tr>
					<td><a onclick="navegacaoSub('documentos/','convite', '');"><i class="circular <?php echo $cor; ?> marker icon"></i>Convite</a></td>
				</tr>				
				<tr>
					<td><a onclick="navegacaoSub('documentos/','casamento', '');"><i class="circular <?php echo $cor; ?> heart icon"></i>Certificado de Casamento</a></td>
				</tr>
				<tr>
					<td><a onclick="navegacaoSub('documentos/','batismo', '');"><i class="circular <?php echo $cor; ?> theme icon"></i>Certificado de Batismo</a></td>
				</tr>
				<tr>
					<td><a onclick="navegacaoSub('documentos/','consagracao', '');"><i class="circular <?php echo $cor; ?> tags icon"></i>Certificado de Consagração</a></td>
				</tr>
				<tr>
					<td><a onclick="navegacaoSub('documentos/','certificado_membro', '');"><i class="circular <?php echo $cor; ?> users icon"></i>Certificado de Membro</a></td>
				</tr>
				<tr>
					<td><a onclick="navegacaoSub('documentos/','certificado_curso', '');"><i class="circular <?php echo $cor; ?> student icon"></i>Certificado de Curso</a></td>
				</tr>
				<tr>
					<td><a onclick="navegacaoSub('documentos/','apresentacao', '');"><i class="circular <?php echo $cor; ?> child icon"></i>Certificado de Apresentação de Criança</a></td>
				</tr>

			</tbody>  
		</table>	

	</div>
</div>