<?php
function inicio(){
	echo "<div class=\"column divForm\" style=\"width:auto; max-width: 450px; float: left; margin: 10px;\">";
}

function fim(){
	echo "</div>";
}
?>
<?php 
	if(isset($dados['retorno'])){
			$retornoJson['valido'] = $dados['retorno'][0];
			$retornoJson['mensagem'] = $dados['retorno'][1];
			$retornoJson['erros'] = isset($dados['retorno'][2]) ? $dados['retorno'][2] : "";

			$retornoJson = json_encode($retornoJson);
			echo $retornoJson;
	
	}else{
?>
<style>
@media (min-width: 460px) {
  .divForm {
    width:450px !important;
  }
}
</style>
  <?php 
    $nomeSingular = "";
    if(isset($dados['nome'][0]))
      $nomeSingular = $dados['nome'][0];
    else
      $nomeSingular = $dados['nomeController'];
  ?>
<div style="width:100%; text-align:center; text-transform: uppercase;">
	<h2> <img style="width:34px; margin-bottom:-5px;" src="<?php echo URL; ?>public/images/icons/funcionario.png">Editar <?php echo $nomeSingular;?></h2>
</div>


<?php 
	$this->html->formulario();

	echo "<div class=\"ui column center aligned grid\">";
 	echo "<input type='text' name='id' value='".$dados['id']."' style='display:none;' />
      <div class=\"column\" style=\"width:auto;\">
        <div class=\"ui left aligned segment\" style=\"\">";

      inicio();
  
      $this->html->campo("membro");
      $this->html->campo("cargo");
      $this->html->campo("salario");
      //$this->html->campo("situacao");

      echo "<div class='field' id='campo_situacao'>
       <label>Situação</label><div class='ui corner labeled left icon input'><div class='ui search dropdown selection' id='select_situacao' onkeypress=\"enterSubmit(event);\" onmouseover=\"registraSelect('select_situacao');\">
              <input type='hidden' name='situacao' value='".$dados['funcionarios']['situacao']."' id='input_situacao' class='validarObrigatorio' onchange=\"validar('situacao');mostrarDtDemissao('1')\" style='max-width:450px; min-width:300px;''>
              <i class='triangle down icon disabled'></i>
              <input class='search' tabindex='0'><div class='text' data-value='' style='max-width:450px; min-width:300px;'></div>
              <div class='menu transition hidden' tabindex='-1' style=''><div class='item active selected' data-value=''></div><div class='item' data-value='Ativo'>Ativo</div><div class='item' data-value='De Ferias'>De Férias</div><div class='item' data-value='Demitido'>Demitido</div>
              </div><div class='ui corner label'><i class='icon asterisk'></i></div>
              </div></div></div>";

      $mostrar = ($dados['funcionarios']['situacao'] == "Demitido") ? "" : "style='display:none'";
      echo "<div id='demissaoId1' $mostrar >";
        $this->html->campo("demissao");
      echo "</div>";
      fim();
      inicio();

  	$this->html->campo("admissao");
  	$selecionado = ($dados['funcionarios']['inss'] == 1) ? "checked='checked'" : "";
	echo "<script type=\"text/javascript\">$(document).ready(function(){ $('.ui.checkbox').checkbox(); });</script>
		<div class='ui checkbox'>
		<input $selecionado name='inss' type='checkbox'>
		<label><strong>Calcular INSS</strong></label>
		</div><br><br>";	
  
  $this->html->campo("descricao");
  
  echo "<div style='clear: both;'>";
  $this->html->submeter(null , "editar", "Salvar Alteração", null, $dados['id']); 
  echo "</div>";
  fim();
  echo "</div>";
	echo "</div>";	
	$this->html->formularioFim(); 
}?>